### PR TITLE
Fix CS-215 and CS-239

### PR DESCRIPTION
**Pull request by bitterdev**

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
There are a lot of CSS changes in here that look unrelated to 215 or 239 like adding padding to the top of dark mode pages only. Are these meant to be included?

**Review by KorvinSzanto — CHANGES_REQUESTED** [review]
Double check that these changes are needed for 215/239 or specify what they are relating to.

**Comment by bitterdev** [comment]
Yes. That's correct. If you check the commit messages there are more changes then just 215 + 239 like described in the title.

- css fixes
- fixes related to CS-215
- Remove date + username; task CS-239
- Fix CS-243
- Fix button height issue (CS-356)

**Comment by aembler** [comment]
Thanks everybody – there's probably some useful things in here but the code base has moved on a bit too much to be merged. We may merge in some of these changes piecemeal but we'll worry about those at those times.

**Pull request closed without merging**
